--- 
jobs: 
  runs-on: ubuntu-latest
  steps: 
    - 
      name: "default deploy"
      uses: appleboy/lambda-action@master
      with: 
        aws_access_key_id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws_region: me-south-1
        aws_secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        function_name: CP-test
name: CI
true: 
  pull_request: 
    branches: 
      - main
  push: 
    branches: 
      - main
